name: Test

on:
  pull_request:
  push:
    branches:
      - "**"

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) 1.6.21
        shell: bash
      - name: Check workflow files
        run: ./actionlint -color
        shell: bash

  lint-cruft:
    name: Check if automatic project update was successful
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fail if .rej files exist as structure update was not successful
        run: test -z "$(find . -iname '*.rej')"

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: dev
      - run: pixi run -e dev pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: dev
      - run: pixi run -e dev pytest

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: dev
      - run: pixi run -e dev mkdocs build
